### ISSUE TITLE
Implement a responsive menu

### ISSUE THREAD

**Issue by fernanev** [DOREMUS-ANR/overture#1]
Replace actual menu by a "hamburger one" when exploring the data on a small screen size.

**Comment by rtroncy** [comment]
By "hamburger menu", you meant something like https://cdn4.iconfinder.com/data/icons/wirecons-free-vector-icons/32/menu-alt-512.png?

**Comment by fernanev** [comment]
Yes, exactly that.

**Comment by pierrechoffe** [comment]
Alternative to PNG here :)
http://webdesign.tutsplus.com/fr/tutorials/7-non-raster-approaches-for-making-the-hamburger-menu-icon--cms-21686
