### ISSUE TITLE
Improvement for docker

### ISSUE THREAD

**Issue by pasqLisena** [DOREMUS-ANR/overture#3]
- [x] **Change the base container**: create our own NodeJS container based on either Ubuntu 16.04 or Alpine 3.3
- [x] Run the app inside the container as **another user than root**
- [x] Run the application from a **shell script**
- [x] **Reduce the size** of the container
- [x] Put the **configuration files** of the app into a **mapped volume**

**Comment by jplu** [comment]
Here are the other improvements:

[ ] run the application from a shell script
[ ] reduce the size of your container
[ ] put the configuration files of your app into a mapped volume

**Comment by jplu** [comment]
Here a better image:

```
FROM jplu/node

# Install app dependencies
COPY . /usr/src/app
WORKDIR /usr/src/app
RUN npm install --production

RUN adduser -D -g sudo nodeuser -u 1000 \
    && chown -R nodeuser /usr/src/app \
    && chmod -R 777 /root \
    && echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers

EXPOSE 3333
CMD [ "sudo", "-E", "-u", "nodeuser", "npm", "run", "prod" ]
```

Most of the requirements have been addressed and this new image is already deployed on rague and makes run the current online app, so no need to rerun Docker over it.
