### ISSUE TITLE
Surrond SPARQL query with try/catch

### ISSUE THREAD

**Issue by pasqLisena** [DOREMUS-ANR/overture#4]
We needs to surround all queries to Virtuoso with `try`/`catch` statements for avoiding that the application crashes with the following error:

```
/usr/src/app/node_modules/sparql-client/lib/client.js:43
            if (error.code == "ECONNREFUSED") {
```

**Comment by rtroncy** [comment]
What sparql client do you use between? What this error means, a connection refused to Virtuoso?

**Comment by pasqLisena** [comment]
I am not sure, something happens in between and the [sparql client](https://github.com/thomasfr/node-sparql-client) we use simply kill the process without logging useful info. I will try to catch the error and print it

**Comment by rtroncy** [comment]
I didn't know you were using this sparql client, it is not written in the README. Did you consider other libraries, I'm more familiar with [sparql.js](https://github.com/RubenVerborgh/SPARQL.js) for example ([node](https://www.npmjs.com/package/sparql-js)).

**Comment by pasqLisena** [comment]
> I'm more familiar with sparql.js for example (node).

This is a parser, more then a client.
